starchaos/likes/models.py
from starchaos import db


class Like(db.Model):
    __tablename__ = 'likes'

    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id', ondelete='CASCADE'), nullable=False)

    def __repr__(self):
        return f"Like(user_id={self.user_id}, post_id={self.post_id})"

starchaos/likes/routes.py
from flask import redirect, request, Blueprint
from starchaos.posts.models import Post
from starchaos import db
from flask_login import current_user, login_required

likes = Blueprint('likes', __name__)


@likes.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)

starchaos/main/routes.py
from flask import render_template, request, Blueprint, redirect, url_for
from starchaos.posts.models import Post
from flask_login import login_required, current_user
from starchaos import db

main = Blueprint('main', __name__)


@main.route("/", methods=['POST', 'GET'])
@main.route("/index", methods=['POST', 'GET'])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', posts=posts)


@main.route('/theme/<string:_theme>')
@login_required
def theme(_theme):
    if _theme == 'light':
        current_user.theme = _theme
        db.session.commit()
    if _theme == 'dark':
        current_user.theme = _theme
        db.session.commit()
    return redirect(request.referrer)

starchaos/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_socketio import emit, join_room
from sqlalchemy.orm import aliased
from sqlalchemy.sql import func
from starchaos import bcrypt, db, socketio
from starchaos.posts.models import Post
from starchaos.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
    ChangePasswordForm
)
from starchaos.posts.forms import PostForm
from starchaos.users.models import User, Message
from starchaos.users.utils import save_image, send_reset_email, get_random_users_not_friends

users = Blueprint('users', __name__)


@users.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(full_name=form.full_name.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'The account has been created! You can now log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/profile', defaults={'full_name': None}, methods=['POST', 'GET'])
@users.route('/profile/<string:full_name>', methods=['POST', 'GET'])
@login_required
def profile(full_name):
    if not full_name:
        full_name = current_user.full_name
    post_form = PostForm()
    if post_form.validate_on_submit():
        post = Post(content=post_form.content.data, author=current_user)
        if post_form.picture.data:
            post_image = save_image(post_form.picture.data, (1500, 1500), 'post_images')
            post.image = post_image
        db.session.add(post)
        db.session.commit()

        flash('Your post has been created!', 'success')
        return redirect(url_for('users.profile', _anchor='iq-top-navbar'))

    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(full_name=full_name).first_or_404()
    friends = user.friends.all()
    random_users = get_random_users_not_friends(user, num_users=10)
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('profile.html', title='Profile', post_form=post_form, posts=posts, user=user,
                           friends=friends, random_users=random_users)


@users.route('/update', methods=['POST', 'GET'])
@login_required
def update():
    form = UpdateAccountForm()
    password_form = ChangePasswordForm()
    _pass = True
    if 'submit' in request.form and request.form['submit'] == 'Update':
        if form.validate_on_submit():
            if form.picture.data:
                profile_image = save_image(form.picture.data, (500, 500), 'profile_images')
                current_user.profile_image = profile_image
            if form.bg_picture.data:
                profile_bg_image = save_image(form.bg_picture.data, (1500, 1500), 'profile_images')
                current_user.bg_image = profile_bg_image
            current_user.full_name = form.full_name.data
            current_user.email = form.email.data
            db.session.commit()
            flash('Your account has been updated!', 'success')
            return redirect(url_for('users.profile'))
    if 'submit' in request.form and request.form['submit'] == 'Change Password':
        _pass = False
        if password_form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(password_form.new_password.data).decode('utf-8')
            current_user.password = hashed_password
            db.session.commit()
            flash('Your password has been updated!', 'success')
            return redirect(url_for('users.profile'))

    if request.method == 'GET':
        form.full_name.data = current_user.full_name
        form.email.data = current_user.email

    return render_template('update.html', title='Update Profile', form=form, password_form=password_form, _pass=_pass)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        return render_template('mail_confirm.html', email=form.email.data)
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/add_friend/<int:user_id>", methods=["POST"])
@login_required
def add_friend(user_id):
    user = User.query.get(user_id)
    if user:
        current_user.add_friend(user)
        flash(f"You are now friends with {user.full_name}!", "success")
    return redirect(request.referrer)


@users.route("/remove_friend/<int:user_id>", methods=["POST"])
@login_required
def remove_friend(user_id):
    user = User.query.get(user_id)
    if user:
        current_user.remove_friend(user)
        flash(f"You are no longer friends with {user.full_name}.", "info")
    return redirect(request.referrer)


@users.route("/chat/<int:receiver_id>")
@login_required
def chat(receiver_id):
    sender = current_user
    receiver = User.query.get(receiver_id)
    messages = Message.query.filter(
        ((Message.sender_id == sender.id) & (Message.receiver_id == receiver_id)) |
        ((Message.sender_id == receiver_id) & (Message.receiver_id == sender.id))
    ).all()
    return render_template('chat.html', sender=sender, receiver=receiver, messages=messages)


@users.route("/delete_messages/<int:receiver_id>", methods=['POST'])
@login_required
def delete_messages(receiver_id):
    sender_id = current_user.id
    Message.query.filter(
        ((Message.sender_id == sender_id) & (Message.receiver_id == receiver_id)) |
        ((Message.sender_id == receiver_id) & (Message.receiver_id == sender_id))
    ).delete()
    db.session.commit()
    return redirect(url_for('users.chats'))


@users.route("/chats")
@login_required
def chats():
    u = aliased(User)
    m = aliased(Message)

    subquery = (
        db.session.query(u.id.label('user_id'), func.max(m.date_posted).label('max_date'))
        .join(m, (u.id == m.sender_id) | (u.id == m.receiver_id))
        .filter((m.sender_id == current_user.id) | (m.receiver_id == current_user.id))
        .filter(u.id != current_user.id)
        .group_by(u.id)
        .distinct(u.id)
        .subquery()
    )

    users_with_messages = (
        db.session.query(u)
        .join(subquery, u.id == subquery.c.user_id)
        .order_by(subquery.c.max_date.desc())
        .all()
    )

    return render_template('chats.html', messaged_users=users_with_messages)


@socketio.on('private_message')
@login_required
def handle_private_message(data):
    sender_id = data['sender_id']
    receiver_id = data['receiver_id']
    content = data['content']

    message = Message(sender_id=sender_id, receiver_id=receiver_id, content=content)
    db.session.add(message)
    db.session.commit()

    emit('response', {'sender_id': sender_id, 'content': content,
                      'date': message.date_posted.strftime('%Y-%m-%d %H:%M')}, room=sender_id)
    emit('response', {'sender_id': sender_id, 'content': content,
                      'date': message.date_posted.strftime('%Y-%m-%d %H:%M')}, room=receiver_id)


@socketio.on('join')
@login_required
def handle_join(data):
    room = data['room']
    join_room(room)

starchaos/templates/includes/flashes.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show mb-3 col-sm-5 mx-auto" role="alert">
    <span> {{ message }}</span>
    <button type="button" class="btn-close" data-bs-dismiss="alert"
            aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

starchaos/templates/includes/footer.html
<footer class="iq-footer bg-white">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                Copyright 2023 <a href="{{ url_for('main.index') }}">StarChaos</a> All Rights Reserved.
            </div>
        </div>
    </div>
</footer>

starchaos/templates/includes/head.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
    <title>StarChaos - {{ title }}</title>
    {% else %}
    <title>StarChaos</title>
    {% endif %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/loader.ico') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/socialv.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='vendor/@fortawesome/fontawesome-free/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/remixicon/fonts/remixicon.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='vendor/vanillajs-datepicker/dist/css/datepicker.min.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css') }}">
</head>

starchaos/templates/includes/likes.html
<div class="comment-area mt-3 d-flex align-items-center">
    {% if current_user.has_liked_post(post) %}
    <a href="{{ url_for('likes.like_action', post_id=post.id, action='unlike') }}">
        <img src="{{ url_for('static', filename='images/icon/01.png') }}"
             class="img-fluid like-pic"
             alt="" style="cursor: pointer;"></a>
    {% else %}
    <a href="{{ url_for('likes.like_action', post_id=post.id, action='like') }}">
        <img src="{{ url_for('static', filename='images/icon/01.png') }}"
             class="img-fluid grayscale-image"
             alt="" style="cursor: pointer;">
    </a>
    {% endif %}
    <span class="mx-1">
        {{ post.likes | length }}
        {% if post.likes | length < 2 %}
            Like
        {% else %}
            Likes
        {% endif %}
    </span>
    <span class="mx-3">
        {{ post.comments | length }}
        {% if post.comments | length < 2 %}
            Comment
        {% else %}
            Comments
        {% endif %}
    </span>
</div>

starchaos/templates/includes/loading.html
<div id="loading">
    <div id="loading-center">
    </div>
</div>

starchaos/templates/includes/navbar.html
<div class="iq-top-navbar">
    <div class="iq-navbar-custom">
        <nav class="navbar navbar-expand-lg navbar-light p-0">
            <div class="iq-navbar-logo d-flex justify-content-between">
                <a href="{{ url_for('main.index') }}">
                    <img src="{{ url_for('static', filename='images/loader.png') }}" class="img-fluid" alt="">
                    <span>StarChaos</span>
                </a>
                <div class="iq-menu-bt align-self-center">
                    <div class="wrapper-menu">
                        <div class="main-circle"><i class="ri-menu-line"></i></div>
                    </div>
                </div>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-label="Toggle navigation">
                <i class="ri-menu-3-line"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav  ms-auto navbar-list">
                    <li>
                        {% if current_user.theme == 'dark' %}
                        <a href="{{ url_for('main.theme', _theme='light') }}"
                           class="d-flex align-items-center"
                           title="Change Theme">
                            <i class="fa fa-sun"></i>
                        </a>
                        {% else %}
                         <a href="{{ url_for('main.theme', _theme='dark') }}"
                           class="d-flex align-items-center"
                           title="Change Theme">
                            <i class="fa fa-moon"></i>
                        </a>
                        {% endif %}
                    </li>
                     <li>
                        <a href="{{ url_for('users.profile', _anchor='post-modal-data') }}"
                           class="d-flex align-items-center"
                           title="Create Post">
                            <i class="ri-profile-line"></i>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="   d-flex align-items-center dropdown-toggle" id="drop-down-arrow"
                           data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{{ url_for('static', filename='images/profile_images/' + current_user.profile_image) }}"
                                 class="img-fluid rounded-circle me-3" alt="user">
                            <div class="caption">
                                <h6 class="mb-0 line-height">{{ current_user.full_name }}</h6>
                            </div>
                        </a>
                        <div class="sub-drop dropdown-menu caption-menu" aria-labelledby="drop-down-arrow">
                            <div class="card shadow-none m-0">
                                <div class="card-header  bg-primary">
                                    <div class="header-title">
                                        <h5 class="mb-0 text-white">Hello {{ current_user.full_name }}</h5>
                                    </div>
                                </div>
                                <div class="card-body p-0 ">
                                    <a href="{{ url_for('users.profile') }}" class="iq-sub-card iq-bg-primary-hover">
                                        <div class="d-flex align-items-center">
                                            <div class="rounded card-icon bg-soft-primary">
                                                <i class="ri-file-user-line"></i>
                                            </div>
                                            <div class="ms-3">
                                                <h6 class="mb-0 ">My Profile</h6>
                                                <p class="mb-0 font-size-12">View personal profile details.</p>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="{{ url_for('users.update') }}" class="iq-sub-card iq-bg-warning-hover">
                                        <div class="d-flex align-items-center">
                                            <div class="rounded card-icon bg-soft-warning">
                                                <i class="ri-profile-line"></i>
                                            </div>
                                            <div class="ms-3">
                                                <h6 class="mb-0 ">Edit Profile</h6>
                                                <p class="mb-0 font-size-12">Modify your personal details.</p>
                                            </div>
                                        </div>
                                    </a>
                                    <div class="d-inline-block w-100 text-center p-3">
                                        <a class="btn btn-primary iq-sign-btn" href="{{ url_for('users.logout') }}"
                                           role="button">Sign
                                            out<i class="ri-login-box-line ms-2"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

starchaos/templates/includes/scripts.html
<script src="{{ url_for('static', filename='js/libs.min.js') }}"></script>
<!-- slider JavaScript -->
<script src="{{ url_for('static', filename='js/slider.js') }}"></script>
<!-- app JavaScript -->
<script src="{{ url_for('static', filename='js/app.js') }}"></script>

starchaos/templates/includes/sidebar.html
<div class="iq-sidebar  sidebar-default ">
    <div id="sidebar-scrollbar">
        <nav class="iq-sidebar-menu">
            <ul id="iq-sidebar-toggle" class="iq-menu">
                <li class="{{ 'active' if request.endpoint == 'main.index' else '' }}">
                    <a href="{{ url_for('main.index') }}">
                        <i class="las la-newspaper"></i><span>Newsfeed</span>
                    </a>
                </li>
                <li class="{{ 'active' if request.endpoint == 'users.profile' and user == current_user else '' }}">
                    <a href="{{ url_for('users.profile') }}">
                        <i class="las la-user"></i><span>Profile</span>
                    </a>
                </li>
                <li class="{{ 'active' if request.endpoint == 'users.chats' else '' }}">
                    <a href="{{ url_for('users.chats') }}">
                        <i class="las la-comments"></i><span>Chats</span>
                    </a>
                </li>
            </ul>
        </nav>
        <div class="p-5"></div>
    </div>
</div>