starchaos/posts/models.py
from datetime import datetime
from starchaos import db


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer(), primary_key=True)
    content = db.Column(db.Text, nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    image = db.Column(db.String(20), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    likes = db.relationship('Like', backref='post', lazy=True, cascade='all, delete-orphan')
    comments = db.relationship('Comment', backref='post', lazy=True, cascade='all, delete-orphan')

    def __repr__(self):
        return f"Post('{self.date_posted}')"

starchaos/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    content = TextAreaField('', validators=[DataRequired()],
                            render_kw={"placeholder": "Write something here..."})
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

starchaos/main/routes.py
from flask import render_template, request, Blueprint, redirect, url_for
from starchaos.posts.models import Post
from flask_login import login_required, current_user
from starchaos import db

main = Blueprint('main', __name__)


@main.route("/", methods=['POST', 'GET'])
@main.route("/index", methods=['POST', 'GET'])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', posts=posts)


@main.route('/theme/<string:_theme>')
@login_required
def theme(_theme):
    if _theme == 'light':
        current_user.theme = _theme
        db.session.commit()
    if _theme == 'dark':
        current_user.theme = _theme
        db.session.commit()
    return redirect(request.referrer)

starchaos/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from starchaos import db
from starchaos.comments.models import Comment
from starchaos.posts.forms import (
    PostForm
)
from starchaos.posts.models import Post
from starchaos.users.utils import save_image

posts = Blueprint('posts', __name__)


@posts.route('/post/<int:post_id>', methods=['POST', 'GET'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id=post.id).order_by(Comment.date_posted.desc())

    if request.method == 'POST':
        content = request.form.get('comment_content')
        if content:
            new_comment = Comment(content=content, user_id=current_user.id, post_id=post_id)
            db.session.add(new_comment)
            db.session.commit()
            flash('Your comment is added!', 'success')
        return redirect(url_for('posts.post', post_id=post_id))

    return render_template('post.html', title='Post', post=post, comments=comments)


@posts.route('/post/<int:post_id>/update', methods=['POST', 'GET'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.content = form.content.data
        if form.picture.data:
            post_image = save_image(form.picture.data, (1500, 1500), 'post_images')
            post.image = post_image
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.content.data = post.content
    return render_template('update_post.html', title='Update Post', post=post, form=form)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))

starchaos/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_socketio import emit, join_room
from sqlalchemy.orm import aliased
from sqlalchemy.sql import func
from starchaos import bcrypt, db, socketio
from starchaos.posts.models import Post
from starchaos.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
    ChangePasswordForm
)
from starchaos.posts.forms import PostForm
from starchaos.users.models import User, Message
from starchaos.users.utils import save_image, send_reset_email, get_random_users_not_friends

users = Blueprint('users', __name__)


@users.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(full_name=form.full_name.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'The account has been created! You can now log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/profile', defaults={'full_name': None}, methods=['POST', 'GET'])
@users.route('/profile/<string:full_name>', methods=['POST', 'GET'])
@login_required
def profile(full_name):
    if not full_name:
        full_name = current_user.full_name
    post_form = PostForm()
    if post_form.validate_on_submit():
        post = Post(content=post_form.content.data, author=current_user)
        if post_form.picture.data:
            post_image = save_image(post_form.picture.data, (1500, 1500), 'post_images')
            post.image = post_image
        db.session.add(post)
        db.session.commit()

        flash('Your post has been created!', 'success')
        return redirect(url_for('users.profile', _anchor='iq-top-navbar'))

    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(full_name=full_name).first_or_404()
    friends = user.friends.all()
    random_users = get_random_users_not_friends(user, num_users=10)
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('profile.html', title='Profile', post_form=post_form, posts=posts, user=user,
                           friends=friends, random_users=random_users)


@users.route('/update', methods=['POST', 'GET'])
@login_required
def update():
    form = UpdateAccountForm()
    password_form = ChangePasswordForm()
    _pass = True
    if 'submit' in request.form and request.form['submit'] == 'Update':
        if form.validate_on_submit():
            if form.picture.data:
                profile_image = save_image(form.picture.data, (500, 500), 'profile_images')
                current_user.profile_image = profile_image
            if form.bg_picture.data:
                profile_bg_image = save_image(form.bg_picture.data, (1500, 1500), 'profile_images')
                current_user.bg_image = profile_bg_image
            current_user.full_name = form.full_name.data
            current_user.email = form.email.data
            db.session.commit()
            flash('Your account has been updated!', 'success')
            return redirect(url_for('users.profile'))
    if 'submit' in request.form and request.form['submit'] == 'Change Password':
        _pass = False
        if password_form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(password_form.new_password.data).decode('utf-8')
            current_user.password = hashed_password
            db.session.commit()
            flash('Your password has been updated!', 'success')
            return redirect(url_for('users.profile'))

    if request.method == 'GET':
        form.full_name.data = current_user.full_name
        form.email.data = current_user.email

    return render_template('update.html', title='Update Profile', form=form, password_form=password_form, _pass=_pass)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        return render_template('mail_confirm.html', email=form.email.data)
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/add_friend/<int:user_id>", methods=["POST"])
@login_required
def add_friend(user_id):
    user = User.query.get(user_id)
    if user:
        current_user.add_friend(user)
        flash(f"You are now friends with {user.full_name}!", "success")
    return redirect(request.referrer)


@users.route("/remove_friend/<int:user_id>", methods=["POST"])
@login_required
def remove_friend(user_id):
    user = User.query.get(user_id)
    if user:
        current_user.remove_friend(user)
        flash(f"You are no longer friends with {user.full_name}.", "info")
    return redirect(request.referrer)


@users.route("/chat/<int:receiver_id>")
@login_required
def chat(receiver_id):
    sender = current_user
    receiver = User.query.get(receiver_id)
    messages = Message.query.filter(
        ((Message.sender_id == sender.id) & (Message.receiver_id == receiver_id)) |
        ((Message.sender_id == receiver_id) & (Message.receiver_id == sender.id))
    ).all()
    return render_template('chat.html', sender=sender, receiver=receiver, messages=messages)


@users.route("/delete_messages/<int:receiver_id>", methods=['POST'])
@login_required
def delete_messages(receiver_id):
    sender_id = current_user.id
    Message.query.filter(
        ((Message.sender_id == sender_id) & (Message.receiver_id == receiver_id)) |
        ((Message.sender_id == receiver_id) & (Message.receiver_id == sender_id))
    ).delete()
    db.session.commit()
    return redirect(url_for('users.chats'))


@users.route("/chats")
@login_required
def chats():
    u = aliased(User)
    m = aliased(Message)

    subquery = (
        db.session.query(u.id.label('user_id'), func.max(m.date_posted).label('max_date'))
        .join(m, (u.id == m.sender_id) | (u.id == m.receiver_id))
        .filter((m.sender_id == current_user.id) | (m.receiver_id == current_user.id))
        .filter(u.id != current_user.id)
        .group_by(u.id)
        .distinct(u.id)
        .subquery()
    )

    users_with_messages = (
        db.session.query(u)
        .join(subquery, u.id == subquery.c.user_id)
        .order_by(subquery.c.max_date.desc())
        .all()
    )

    return render_template('chats.html', messaged_users=users_with_messages)


@socketio.on('private_message')
@login_required
def handle_private_message(data):
    sender_id = data['sender_id']
    receiver_id = data['receiver_id']
    content = data['content']

    message = Message(sender_id=sender_id, receiver_id=receiver_id, content=content)
    db.session.add(message)
    db.session.commit()

    emit('response', {'sender_id': sender_id, 'content': content,
                      'date': message.date_posted.strftime('%Y-%m-%d %H:%M')}, room=sender_id)
    emit('response', {'sender_id': sender_id, 'content': content,
                      'date': message.date_posted.strftime('%Y-%m-%d %H:%M')}, room=receiver_id)


@socketio.on('join')
@login_required
def handle_join(data):
    room = data['room']
    join_room(room)

starchaos/templates/auth_base.html
<!doctype html>
<html lang="en">
{% include 'includes/head.html' %}
<body>
<!-- loader Start -->
{% include 'includes/loading.html' %}
<!-- loader END -->
<!-- Wrapper Start -->
{% include 'includes/flashes.html' %}

<div class="wrapper">
    <section class="sign-in-page">
        <div id="container-inside">
            <div id="circle-small"></div>
            <div id="circle-medium"></div>
            <div id="circle-large"></div>
            <div id="circle-xlarge"></div>
            <div id="circle-xxlarge"></div>
        </div>
        <div class="container p-0">
            <div class="row no-gutters">
                <div class="col-md-6 text-center pt-5">
                    <div class="sign-in-detail text-white">
                        <h2>
                            <a class="sign-in-logo mb-5" style="color: black;" href="{{ url_for('users.login') }}">
                                <img
                                    src="{{ url_for('static', filename='images/loader.png') }}" class="img-fluid"
                                    alt="logo">StarChaos</a>
                        </h2>
                        <div class="sign-slider overflow-hidden ">
                            <ul class="swiper-wrapper list-inline m-0 p-0 ">
                                <li class="swiper-slide">
                                    <img src="{{ url_for('static', filename='images/login/1.png') }}"
                                         class="img-fluid mb-4" alt="logo">
                                    <h4 class="mb-1 text-white">Find new friends</h4>
                                    <p>It is a long established fact that a reader will be distracted by the readable
                                        content.</p>
                                </li>
                                <li class="swiper-slide">
                                    <img src="{{ url_for('static', filename='images/login/2.png') }}"
                                         class="img-fluid mb-4" alt="logo">
                                    <h4 class="mb-1 text-white">Connect with the world</h4>
                                    <p>It is a long established fact that a reader will be distracted by the readable
                                        content.</p>
                                </li>
                                <li class="swiper-slide">
                                    <img src="{{ url_for('static', filename='images/login/3.png') }}"
                                         class="img-fluid mb-4" alt="logo">
                                    <h4 class="mb-1 text-white">Create new events</h4>
                                    <p>It is a long established fact that a reader will be distracted by the readable
                                        content.</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>

</div>
<!-- Wrapper End-->
<!-- Backend Bundle JavaScript -->
{% include 'includes/scripts.html' %}
</body>
</html>

starchaos/templates/base.html
<!doctype html>
{% if current_user.theme == 'dark' %}
<html lang="en" class="invert-html">
{% else %}
<html lang="en">
{% endif %}
{% include 'includes/head.html' %}
<body>
<!-- loader Start -->
{% include 'includes/loading.html' %}
<!-- loader END -->
<!-- Wrapper Start -->

<div class="wrapper">
    {% include 'includes/sidebar.html' %}
    {% include 'includes/navbar.html' %}
    <div id="content-page" class="content-page">
        {% include 'includes/flashes.html' %}
        {% block content %}
        {% endblock %}
    </div>
</div>
<!-- Wrapper End-->
{% include 'includes/footer.html' %}
<!-- Backend Bundle JavaScript -->
{% include 'includes/scripts.html' %}
</body>
</html>

starchaos/templates/chats.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body chat-page p-0">
                    <div class="chat-data-block">
                        <div class="row">
                            <div class="col-lg-12 chat-data-right scroller">
                                <div class="chat-search pt-3 ps-3">
                                    <div class="d-flex align-items-center">
                                        <div class="chat-profile me-3">
                                            <img src="{{ url_for('static', filename='images/profile_images/' + current_user.profile_image) }}"
                                                 alt="chat-user" class="avatar-60 ">
                                        </div>
                                        <div class="chat-caption">
                                            <h5 class="mb-0">{{ current_user.full_name }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-sidebar-channel scroller mt-4 ps-3">
                                    <h5 class="mt-3">Direct Messages</h5>
                                    <ul class="iq-chat-ui nav flex-column nav-pills">
                                        {% for user in messaged_users %}
                                        <li class="d-flex justify-content-between" style="border-bottom: 1px solid #dee2e6;">
                                            <a href="{{ url_for('users.chat', receiver_id=user.id) }}"
                                               style="border: none; width: 100%;">
                                                <div class="d-flex align-items-center">
                                                    <div class="avatar me-2">
                                                        <img src="{{ url_for('static', filename='images/profile_images/' + user.profile_image) }}"
                                                             alt="chatuserimage"
                                                             class="avatar-50 ">
                                                    </div>
                                                    <div class="chat-sidebar-name">
                                                        <h6 class="mb-0">{{ user.full_name }}</h6>
                                                    </div>
                                                </div>
                                            </a>
                                            <div class="card-header-toolbar d-flex align-items-center">
                                                <div class="dropdown">
                                                   <span class="dropdown-toggle btn btn-secondary me-2"
                                                         id="dropdownMenuButton01" data-bs-toggle="dropdown"
                                                         aria-expanded="true" role="button">
                                                   <i class="ri-check-line me-1 text-white"></i> Action
                                                   </span>
                                                    <div class="dropdown-menu dropdown-menu-right"
                                                         aria-labelledby="dropdownMenuButton01">
                                                        <form action="{{ url_for('users.delete_messages', receiver_id=user.id) }}"
                                                              method="POST">
                                                            <button type="submit"
                                                                    class="btn btn-danger w-100">
                                                                Delete Chat For Everyone
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        {% else %}
                                        <li>No messages.</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

starchaos/templates/errors_base.html
<!doctype html>
<html lang="en">
{% include 'includes/head.html' %}
<body>
<div class="wrapper">
    <div class="container p-0">
        <div class="row no-gutters height-self-center">
            <div class="col-sm-12 text-center align-self-center">
                <div class="iq-error position-relative mt-5">
                    <img src="{{ url_for('static', filename='images/error/02.png') }}" class="img-fluid iq-error-img" alt="">
                    {% block content %}
                    {% endblock %}
                    <a class="btn btn-primary mt-3" href="{{ url_for('main.index') }}"><i class="ri-home-4-line"></i>Back
                        to Home</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Backend Bundle JavaScript -->
{% include 'includes/scripts.html' %}
</body>
</html>

starchaos/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 row m-0 p-0">
            <div class="col-sm-8 mx-auto">
                <div class="card card-block card-stretch card-height">
                    {% for post in posts.items %}
                    <div class="card-body">
                        <div class="user-post-data">
                            <div class="d-flex justify-content-between">

                                <div class="me-3">
                                    <img class="rounded-circle img-fluid"
                                         src="{{ url_for('static', filename='images/profile_images/' + post.author.profile_image) }}"
                                         alt="" style="max-width: unset; height: 50px; width: 50px;">
                                </div>
                                <div class="w-100">
                                    <div class="d-flex justify-content-between">
                                        <div class="">
                                            <a href="{{ url_for('users.profile', full_name=post.author.full_name) }}">
                                                <h5 class="mb-0 d-inline-block">{{ post.author.full_name }}</h5>
                                                <p class="mb-0 text-gray">{{ post.date_posted.strftime('%Y-%m-%d')
                                                    }}</p>
                                            </a>
                                        </div>
                                        <div class="card-post-toolbar">
                                            <div class="dropdown">
                                                   <span class="dropdown-toggle" data-bs-toggle="dropdown"
                                                         aria-haspopup="true" aria-expanded="false" role="button">
                                                   <i class="ri-more-fill"></i>
                                                   </span>
                                                <div class="dropdown-menu m-0 p-0">
                                                    <a class="dropdown-item p-3"
                                                       href="{{ url_for('posts.post', post_id=post.id) }}">
                                                        <div class="d-flex align-items-top">
                                                            <i class="fa fa-eye h4"></i>
                                                            <div class="data ms-2">
                                                                <h6>Check the post</h6>
                                                                <p class="mb-0">Maybe you will like it!</p>
                                                            </div>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="mt-3">
                            <p>{{ post.content }}</p>
                        </div>
                        <div class="user-post">
                            {% if post.image %}
                            <img src="{{ url_for('static', filename='images/post_images/' + post.image) }}"
                                 alt="post-image"
                                 class="img-fluid w-100"/>
                            {% endif %}
                        </div>
                        {% include 'includes/likes.html' %}
                    </div>
                    {% else %}
                    <h2>No posts. <a href="{{ url_for('users.profile', _anchor='post-modal-data') }}">Add one!</a></h2>
                    {% endfor %}
                </div>
            </div>

        </div>

    </div>
    <div class="d-flex justify-content-center">
        {% if posts.pages > 1 %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-info mb-4 mx-1" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4 mx-1" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}

starchaos/templates/login.html
{% extends 'auth_base.html' %}
{% from 'macro/_renderfield.html' import renderfield %}

{% block content %}
<div class="col-md-6 bg-white pt-5 pt-5 pb-lg-0 pb-5">
    <div class="sign-in-from">
        <h1 class="mb-0">Sign in</h1>
        <form class="mt-4" method="POST">
            {{ form.hidden_tag() }}
            {{ renderfield(form.email) }}
            {{ renderfield(form.password) }}
            <div class="d-inline-block w-100">
            </div>
            <div class="d-inline-block w-100">
                <div class="form-check d-inline-block mt-2 pt-1">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
                {{ form.submit(class="btn btn-primary float-end") }}
                <div>
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    </small>
                </div>
            </div>
            <div class="sign-info">
                <span class="dark-color d-inline-block line-height-2">Don't have an account?
                    <a href="{{ url_for('users.register') }}">Sign up</a></span>
            </div>
        </form>
    </div>
</div>
{% endblock %}

starchaos/templates/mail_confirm.html
{% extends 'auth_base.html' %}

{% block content %}
<div class="col-md-6 bg-white pt-5 pt-5 pb-lg-0 pb-5">
    <div class="sign-in-from">
        <img src="../assets/images/login/mail.png" width="80" alt="">
        <h1 class="mt-3 mb-0">Success !</h1>
        <p>A email has been sent to {{ email }}. Please check for an email from company and click on the
            included link to reset your password.</p>
        <div class="d-inline-block w-100">
            <a href="{{ url_for('main.index') }}" class="btn btn-primary mt-3">Back to Home</a>
        </div>
    </div>
</div>
{% endblock %}

starchaos/templates/register.html
{% extends 'auth_base.html' %}
{% from 'macro/_renderfield.html' import renderfield %}

{% block content %}
<div class="col-md-6 bg-white pt-5 pt-5 pb-lg-0 pb-5">
    <div class="sign-in-from">
        <h1 class="mb-0">Sign Up</h1>
        <form class="mt-4" method="POST">
            {{ form.hidden_tag()  }}
            {{ renderfield(form.full_name) }}
            {{ renderfield(form.email) }}
            {{ renderfield(form.password) }}
            {{ renderfield(form.confirm_password) }}
            <div class="d-inline-block w-100">
                {{ form.submit(class="btn btn-primary float-end") }}
            </div>
            <div class="sign-info">
                <span class="dark-color d-inline-block line-height-2">Already Have Account ?
                    <a href="{{ url_for('users.login') }}">Log In</a>
                </span>
            </div>
        </form>
    </div>
</div>
{% endblock %}

starchaos/templates/reset_request.html
{% extends 'auth_base.html' %}
{% from 'macro/_renderfield.html' import renderfield %}

{% block content %}
<div class="col-md-6 bg-white pt-5 pt-5 pb-lg-0 pb-5">
    <div class="sign-in-from">
        <h1 class="mb-0">Reset Password</h1>
        <p>Enter your email address and we'll send you an email with instructions to reset your password.</p>
        <form class="mt-4" method="POST">
            {{ form.hidden_tag()  }}
            {{ renderfield(form.email) }}
            <div class="d-inline-block w-100">
                {{ form.submit(class="btn btn-primary float-right") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}